server:
  port: 8096

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:8098/eureka/

spring:
  application:
    name: web-servive
  cloud:
    loadbalancer:
      retry:
        enabled: false